#!/usr/bin/env python3
"""§9.0 Edge Research analysis — generates config/edge_profile.toml and summary.md."""

from __future__ import annotations

import argparse
from datetime import datetime, timezone
from pathlib import Path
from typing import Dict, List, Tuple

import pandas as pd

FEE_ROUND_TRIP_BPS = 11.0  # futures taker x2 ~0.11%
SLIPPAGE_BPS = 5.0
IMPULSE_MIN_BPS = 5.0
INJECTED_LATENCY_MS = 150


def load_parquet(data_dir: Path) -> pd.DataFrame:
    files = sorted(data_dir.glob("*.parquet"))
    if not files:
        raise FileNotFoundError(f"No parquet in {data_dir}")
    frames = [pd.read_parquet(f) for f in files]
    df = pd.concat(frames, ignore_index=True)
    df["ts_ms"] = df["ts_ms"].astype("int64")
    return df.sort_values("ts_ms")


def compute_follow_through(df: pd.DataFrame) -> pd.DataFrame:
    """Estimate follow-through using forward mid moves on impulse events."""
    events = df[df["impulse_bps_100ms"].abs() >= IMPULSE_MIN_BPS].copy()
    if events.empty:
        return events
    events["direction"] = events["impulse_bps_100ms"].apply(lambda x: 1 if x > 0 else -1)
    # proxy: next 300ms bybit move vs direction (shift within symbol)
    events = events.sort_values(["symbol", "ts_ms"])
    events["bybit_fwd"] = events.groupby("symbol")["bybit_mid"].shift(-3)
    events["fwd_bps"] = (events["bybit_fwd"] - events["bybit_mid"]) / events["bybit_mid"] * 10_000
    events["aligned"] = events["fwd_bps"] * events["direction"] > 0
    return events


def net_edge_by_hour(events: pd.DataFrame) -> pd.DataFrame:
    if events.empty:
        return pd.DataFrame()
    g = events.groupby(["symbol", "hour_utc"]).agg(
        follow_through_rate=("aligned", "mean"),
        conditional_return_bps=("fwd_bps", lambda s: s.abs().mean()),
        n=("aligned", "count"),
    ).reset_index()
    g["net_edge_bps"] = g["conditional_return_bps"] - FEE_ROUND_TRIP_BPS - SLIPPAGE_BPS
    return g


def build_edge_profile(summary: pd.DataFrame) -> Tuple[str, str, Dict]:
    meta_status = "fail"
    edge_sections: Dict[str, dict] = {}
    report_lines = ["# Edge Research Summary", ""]

    for symbol in summary["symbol"].unique():
        sym_df = summary[summary["symbol"] == symbol]
        positive = sym_df[sym_df["net_edge_bps"] > 0]
        hours = sorted(positive["hour_utc"].astype(int).tolist())
        best_net = sym_df["net_edge_bps"].max() if not sym_df.empty else 0.0
        ft_min = sym_df["follow_through_rate"].quantile(0.25) if len(sym_df) > 0 else 0.4
        edge_sections[symbol] = {
            "net_edge_bps": round(float(best_net), 2),
            "follow_through_min": round(float(ft_min), 3),
            "lag_min_bps": 3.0,
            "trade_hours_utc": hours,
            "vol_regime_min_atr_pct": 0.0025,
        }
        report_lines.append(f"## {symbol}")
        report_lines.append(f"- best net_edge_bps: {best_net:.2f}")
        report_lines.append(f"- positive hours: {hours}")
        report_lines.append(f"- follow_through_min: {ft_min:.3f}")
        report_lines.append("")

        if best_net > 0 and len(hours) >= 3:
            meta_status = "pass"

    meta = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "research_period_days": 0,
        "injected_latency_ms": INJECTED_LATENCY_MS,
        "status": meta_status,
    }
    return meta_status, "\n".join(report_lines), meta, edge_sections


def write_toml(path: Path, meta: dict, edges: Dict[str, dict]) -> None:
    lines = [
        "# Auto-generated by research/edge_report/analyze.py",
        "",
        "[meta]",
    ]
    for k, v in meta.items():
        if isinstance(v, str):
            lines.append(f'{k} = "{v}"')
        elif isinstance(v, list):
            lines.append(f"{k} = {v}")
        else:
            lines.append(f"{k} = {v}")
    for sym, cfg in edges.items():
        lines.append("")
        lines.append(f"[edge.{sym}]")
        for k, v in cfg.items():
            if isinstance(v, list):
                lines.append(f"{k} = {v}")
            else:
                lines.append(f"{k} = {v}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_synthetic(data_dir: Path, symbols: List[str], rows_per_symbol: int = 5000) -> None:
    """Dev/CI fixture when live collection unavailable."""
    import numpy as np

    data_dir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(42)
    now = int(datetime.now(timezone.utc).timestamp() * 1000)
    for sym in symbols:
        ts = np.arange(rows_per_symbol) * 100 + now
        base = 67000.0 if sym == "BTCUSDT" else 3500.0
        noise = rng.normal(0, 0.0002, rows_per_symbol)
        b_mid = base * (1 + np.cumsum(noise))
        y_mid = b_mid * (1 + rng.normal(0.0001, 0.00005, rows_per_symbol))
        imp = np.zeros(rows_per_symbol)
        imp[::50] = rng.choice([-8.0, 8.0], size=imp[::50].shape[0])
        hours = (ts // 3_600_000) % 24
        df = pd.DataFrame(
            {
                "ts_ms": ts,
                "symbol": sym,
                "hour_utc": hours.astype(int),
                "binance_mid": b_mid,
                "bybit_mid": y_mid,
                "lag_bps": (b_mid - y_mid) / y_mid * 10_000,
                "impulse_bps_100ms": imp,
                "atr_pct": np.abs(imp) / 100,
            }
        )
        out = data_dir / f"{sym}_synthetic.parquet"
        df.to_parquet(out, index=False)
        print(f"Synthetic fixture: {out}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=Path("research/data"))
    parser.add_argument("--output-profile", type=Path, default=Path("config/edge_profile.toml"))
    parser.add_argument("--output-summary", type=Path, default=Path("research/edge_report/summary.md"))
    parser.add_argument("--synthetic", action="store_true", help="Generate dev fixture data")
    parser.add_argument("--symbols", nargs="+", default=["BTCUSDT", "ETHUSDT"])
    args = parser.parse_args()

    if args.synthetic:
        generate_synthetic(args.data_dir, args.symbols)
    elif not list(args.data_dir.glob("*.parquet")):
        raise SystemExit(
            f"No parquet in {args.data_dir}. Run collector or pass --synthetic for CI."
        )

    df = load_parquet(args.data_dir)
    days = (df["ts_ms"].max() - df["ts_ms"].min()) / 86_400_000
    events = compute_follow_through(df)
    summary = net_edge_by_hour(events)
    status, report, meta, edges = build_edge_profile(summary)
    meta["research_period_days"] = max(1, int(days))

    args.output_summary.parent.mkdir(parents=True, exist_ok=True)
    args.output_summary.write_text(report + f"\n**Status:** {status}\n", encoding="utf-8")
    write_toml(args.output_profile, meta, edges)
    print(f"Profile -> {args.output_profile} status={status}")


if __name__ == "__main__":
    main()
